# Generated by Django 4.0.2 on 2022-02-15 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_groups_userprofile_is_superuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchedcities',
            old_name='date_receita',
            new_name='date',
        ),
    ]
